all:
	make -C datamining/correlation
	make -C datamining/covariance
	make -C linear-algebra/kernels/2mm
	make -C linear-algebra/kernels/3mm
	make -C linear-algebra/kernels/atax
	make -C linear-algebra/kernels/bicg
	make -C linear-algebra/kernels/doitgen
	make -C linear-algebra/kernels/mvt
	make -C linear-algebra/blas/gemm
	make -C linear-algebra/blas/gemver
	make -C linear-algebra/blas/gesummv
	make -C linear-algebra/blas/symm
	make -C linear-algebra/blas/syr2k
	make -C linear-algebra/blas/syrk
	make -C linear-algebra/blas/trmm
	make -C linear-algebra/solvers/cholesky
	make -C linear-algebra/solvers/durbin
	make -C linear-algebra/solvers/gramschmidt
	make -C linear-algebra/solvers/lu
	make -C linear-algebra/solvers/ludcmp
	make -C linear-algebra/solvers/trisolv
	make -C medley/deriche
	make -C medley/floyd-warshall
	make -C medley/nussinov
	make -C stencils/adi
	make -C stencils/fdtd-2d
	make -C stencils/heat-3d
	make -C stencils/jacobi-1d
	make -C stencils/jacobi-2d
	make -C stencils/seidel-2d

clean:
	make -C datamining/correlation clean
	make -C datamining/covariance clean
	make -C linear-algebra/kernels/2mm clean
	make -C linear-algebra/kernels/3mm clean
	make -C linear-algebra/kernels/atax clean
	make -C linear-algebra/kernels/bicg clean
	make -C linear-algebra/kernels/doitgen clean
	make -C linear-algebra/kernels/mvt clean
	make -C linear-algebra/blas/gemm clean
	make -C linear-algebra/blas/gemver clean
	make -C linear-algebra/blas/gesummv clean
	make -C linear-algebra/blas/symm clean
	make -C linear-algebra/blas/syr2k clean
	make -C linear-algebra/blas/syrk clean
	make -C linear-algebra/blas/trmm clean
	make -C linear-algebra/solvers/cholesky clean
	make -C linear-algebra/solvers/durbin clean
	make -C linear-algebra/solvers/gramschmidt clean
	make -C linear-algebra/solvers/lu clean
	make -C linear-algebra/solvers/ludcmp clean
	make -C linear-algebra/solvers/trisolv clean
	make -C medley/deriche clean
	make -C medley/floyd-warshall clean
	make -C medley/nussinov clean
	make -C stencils/adi clean
	make -C stencils/fdtd-2d clean
	make -C stencils/heat-3d clean
	make -C stencils/jacobi-1d clean
	make -C stencils/jacobi-2d clean
	make -C stencils/seidel-2d clean
